# Ann example

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_16fc5346f1da462ba2137308d372953f = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='3YtH9s6P9cB0hXjTqv9CzytpiCi6XsxFkvlfkZ-s8zTp',
    ibm_auth_endpoint="https://iam.eu-gb.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_16fc5346f1da462ba2137308d372953f.get_object(Bucket='cnnproject-donotdelete-pr-tzmtmgmuvpgltn',Key='Churn_Modelling.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [6]:
dataset.fillna(dataset['CreditScore'].mean(),inplace = True)
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [7]:
x= dataset.iloc[:,3:13].values

In [8]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y = dataset.iloc[:,13:].values

In [10]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [11]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x[:,1]=lb.fit_transform(x[:,1])

In [12]:
lb1 = LabelEncoder()
x[:,2]=lb1.fit_transform(x[:,2])

In [13]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder(categorical_features=[1])
x = oh.fit_transform(x).toarray()

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [15]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [16]:
x=x[:,1:] #removing dummy variable (1st column)

In [17]:
x

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [18]:
from sklearn.model_selection import train_test_split                #previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc1 = StandardScaler()
x_train = sc1.fit_transform(x_train)
x_test = sc1.transform(x_test)

In [20]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [21]:
model = Sequential()

# if you want to print colums in x

In [22]:
x_train.shape

(7000, 11)

adding layers  belowis the input layer

In [23]:
model.add(Dense(input_dim=11,init="random_uniform",activation='relu',output_dim=6))

Instructions for updating:
Colocations handled automatically by placer.


/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=6, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


# adding hidden layer

In [24]:
model.add(Dense(init="random_uniform",activation='relu',output_dim=6))

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


# adding output layer

In [25]:
model.add(Dense(output_dim=1,init="random_uniform",activation='sigmoid'))

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


# if you use sigmoid the output will be from 0 to 1 then we will write threshold

# for calculating error we will use binary cross entropy or Log loss

# compile the model

In [26]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# standard scalar  or future scaling mainly for classification

In [27]:
model.fit(x_train,y_train,epochs=2,batch_size=32)

Instructions for updating:
Use tf.cast instead.
Epoch 1/2
7000/7000 [==============================] - 163s 23ms/step - loss: 0.5832 - acc: 0.7977
Epoch 2/2
7000/7000 [==============================] - 157s 22ms/step - loss: 0.4382 - acc: 0.7977


In [28]:
y_pred = model.predict(x_test)

In [29]:
y_pred.min()

0.00740242

In [30]:
y_pred = (y_pred>0.5)

In [31]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [32]:
y_p = model.predict(np.array([[0,1,100,1,25,8,115000,24,1,1,100000]]))

In [33]:
y_p

array([[0.]], dtype=float32)

In [34]:
y_p = (y_p>0.5)

In [35]:
y_p

array([[False]])

In [36]:
model.save("sampleannmodel.h5")

In [37]:
!tar -zcvf sampleannmodel.tgz sampleannmodel.h5

sampleannmodel.h5


In [39]:
!pip install watson_machine_learning_client

In [40]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [41]:
wml_credentials = {
  "apikey": "YEL-2znnNyDyaErzB4Tr2USCdO9KEyPfYOPEscXDovPo",
  "iam_apikey_description": "Auto-generated for key 376159c9-8209-4f8c-8eda-c4eeb362001f",
  "iam_apikey_name": "wdp-writer",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Writer",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/d975b9e8f37b4e63a61175e6574ebf1c::serviceid:ServiceId-6389081e-9cc9-4bb8-8091-e72373bd1c13",
  "instance_id": "85044b4e-3cfe-4a49-a4b7-3a6fafc2b2b0",
  "url": "https://eu-gb.ml.cloud.ibm.com"  
}

In [42]:
client = WatsonMachineLearningAPIClient(wml_credentials)

In [66]:
!pip install tensorflow==1.15

     |████████████████████████████████| 412.3MB 87kB/s s eta 0:00:01    |█████▍                          | 69.9MB 53.6MB/s eta 0:00:07     |██████████▌                     | 134.7MB 55.7MB/s eta 0:00:05��██████████████▊             | 241.2MB 54.6MB/s eta 0:00:04███████████████▍          | 275.9MB 56.6MB/s eta 0:00:03     |███████████████████████▏        | 298.6MB 56.6MB/s eta 0:00:03
     |████████████████████████████████| 3.8MB 41.5MB/s eta 0:00:01
     |████████████████████████████████| 512kB 43.7MB/s eta 0:00:01
     |████████████████████████████████| 51kB 25.2MB/s eta 0:00:01
  Stored in directory: /home/dsxuser/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled t

In [67]:
metadata = {
    client.repository.ModelMetaNames.DESCRIPTION: 'SAMPLE DESCRIPTION',
    client.repository.ModelMetaNames.AUTHOR_NAME: 'swathi',
    client.repository.ModelMetaNames.NAME: "keras model",
    client.repository.ModelMetaNames.FRAMEWORK_NAME: "tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_VERSION: "1.15",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES: [{'name':'keras', 'version': '2.2.4'}]
}

In [68]:
model_details = client.repository.store_model(model="sampleannmodel.tgz",meta_props=metadata)

In [69]:
model_uid = model_details['metadata']['guid']
model_deploy = client.deployments.create(artifact_uid=model_uid,name="ann")



#######################################################################################

Synchronous deployment creation for uid: 'da360a3d-2efa-4d32-876d-2478583ce570' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='c87274d8-e4aa-4b53-8da3-3155e4dd46ca'
------------------------------------------------------------------------------------------------




In [62]:
import tensorflow as tf

print(tf.version.VERSION)

1.13.1


In [50]:
#!pip install keras==2.2.4

In [70]:
scoring_endpoint = client.deployments.get_scoring_url(model_deploy)

In [71]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/85044b4e-3cfe-4a49-a4b7-3a6fafc2b2b0/deployments/c87274d8-e4aa-4b53-8da3-3155e4dd46ca/online'